### ISSUE TITLE
How do I host this

### ISSUE THREAD

**Issue by CodyKoInABox** [CodyKoInABox/randomnumberAPI#2]
How and where can I deploy and host this API for free? I've tried Vercel and Netlify but it didn't work. Heroku isn't free anymore so it's not an option.

**Comment by rdeepc** [comment]
Hi @CodyKoInABox,

Added Vercel deployment support [Pull request #3 ](https://github.com/CodyKoInABox/randomnumberAPI/pull/3)

**Comment by peekeah** [comment]
you can use onrender, it's alternative to heroku.

**Comment by CodyKoInABox** [comment]
> Hi @CodyKoInABox,
> 
> Added Vercel deployment support [Pull request #3 ](https://github.com/CodyKoInABox/randomnumberAPI/pull/3)
